# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@ampproject/remapping-2.3.0" = {
      name = "_at_ampproject_slash_remapping";
      packageName = "@ampproject/remapping";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ampproject/remapping/-/remapping-2.3.0.tgz";
        sha512 = "30iZtAPgz+LTIYoeivqYo853f02jBYSd5uGnGpkFV0M3xOt9aN73erkgYAmZU43x4VfqcnLxW9Kpg3R5LC4YYw==";
      };
    };
    "@antfu/utils-0.7.8" = {
      name = "_at_antfu_slash_utils";
      packageName = "@antfu/utils";
      version = "0.7.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@antfu/utils/-/utils-0.7.8.tgz";
        sha512 = "rWQkqXRESdjXtc+7NRfK9lASQjpXJu1ayp7qi1d23zZorY+wBHVLHHoVcMsEnkqEBWTFqbztO7/QdJFzyEcLTg==";
      };
    };
    "@jridgewell/gen-mapping-0.3.5" = {
      name = "_at_jridgewell_slash_gen-mapping";
      packageName = "@jridgewell/gen-mapping";
      version = "0.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/gen-mapping/-/gen-mapping-0.3.5.tgz";
        sha512 = "IzL8ZoEDIBRWEzlCcRhOaCupYyN5gdIK+Q6fbFdPDg6HqX6jpkItn7DFIpW9LQzXG6Df9sA7+OKnq0qlz/GaQg==";
      };
    };
    "@jridgewell/resolve-uri-3.1.2" = {
      name = "_at_jridgewell_slash_resolve-uri";
      packageName = "@jridgewell/resolve-uri";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/resolve-uri/-/resolve-uri-3.1.2.tgz";
        sha512 = "bRISgCIjP20/tbWSPWMEi54QVPRZExkuD9lJL+UIxUKtwVJA8wW1Trb1jMs1RFXo1CBTNZ/5hpC9QvmKWdopKw==";
      };
    };
    "@jridgewell/set-array-1.2.1" = {
      name = "_at_jridgewell_slash_set-array";
      packageName = "@jridgewell/set-array";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/set-array/-/set-array-1.2.1.tgz";
        sha512 = "R8gLRTZeyp03ymzP/6Lil/28tGeGEzhx1q2k703KGWRAI1VdvPIXdG70VJc2pAMw3NA6JKL5hhFu1sJX0Mnn/A==";
      };
    };
    "@jridgewell/sourcemap-codec-1.4.15" = {
      name = "_at_jridgewell_slash_sourcemap-codec";
      packageName = "@jridgewell/sourcemap-codec";
      version = "1.4.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/sourcemap-codec/-/sourcemap-codec-1.4.15.tgz";
        sha512 = "eF2rxCRulEKXHTRiDrDy6erMYWqNw4LPdQ8UQA4huuxaQsVeRPFl2oM8oDGxMFhJUWZf9McpLtJasDDZb/Bpeg==";
      };
    };
    "@jridgewell/trace-mapping-0.3.25" = {
      name = "_at_jridgewell_slash_trace-mapping";
      packageName = "@jridgewell/trace-mapping";
      version = "0.3.25";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/trace-mapping/-/trace-mapping-0.3.25.tgz";
        sha512 = "vNk6aEwybGtawWmy/PzwnGDOjCkLWSD2wqvjGGAgOAwCGWySYXfYoxt00IJkTF+8Lb57DwOb3Aa0o9CApepiYQ==";
      };
    };
    "@nodelib/fs.scandir-2.1.5" = {
      name = "_at_nodelib_slash_fs.scandir";
      packageName = "@nodelib/fs.scandir";
      version = "2.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.scandir/-/fs.scandir-2.1.5.tgz";
        sha512 = "vq24Bq3ym5HEQm2NKCr3yXDwjc7vTsEThRDnkp2DK9p1uqLR+DHurm/NOTo0KG7HYHU7eppKZj3MyqYuMBf62g==";
      };
    };
    "@nodelib/fs.stat-2.0.5" = {
      name = "_at_nodelib_slash_fs.stat";
      packageName = "@nodelib/fs.stat";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.stat/-/fs.stat-2.0.5.tgz";
        sha512 = "RkhPPp2zrqDAQA/2jNhnztcPAlv64XdhIp7a7454A5ovI7Bukxgt7MX7udwAu3zg1DcpPU0rz3VV1SeaqvY4+A==";
      };
    };
    "@nodelib/fs.walk-1.2.8" = {
      name = "_at_nodelib_slash_fs.walk";
      packageName = "@nodelib/fs.walk";
      version = "1.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.walk/-/fs.walk-1.2.8.tgz";
        sha512 = "oGB+UxlgWcgQkgwo8GcEGwemoTFt3FIO9ababBmaGwXIoBKZ+GTy0pP185beGg7Llih/NSHSV2XAs1lnznocSg==";
      };
    };
    "@rollup/pluginutils-5.1.0" = {
      name = "_at_rollup_slash_pluginutils";
      packageName = "@rollup/pluginutils";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@rollup/pluginutils/-/pluginutils-5.1.0.tgz";
        sha512 = "XTIWOPPcpvyKI6L1NHo0lFlCyznUEyPmPY1mc3KpPVDYulHSTvyeLNVW00QTLIAFNhR3kYnJTQHeGqU4M3n09g==";
      };
    };
    "@types/estree-1.0.5" = {
      name = "_at_types_slash_estree";
      packageName = "@types/estree";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/estree/-/estree-1.0.5.tgz";
        sha512 = "/kYRxGDLWzHOB7q+wtSUQlFrtcdUccpfy+X+9iMBpHK8QLLhx2wIPYuS5DYtR9Wa/YlZAbIovy7qVdB1Aq6Lyw==";
      };
    };
    "@unocss/autocomplete-0.46.5" = {
      name = "_at_unocss_slash_autocomplete";
      packageName = "@unocss/autocomplete";
      version = "0.46.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/autocomplete/-/autocomplete-0.46.5.tgz";
        sha512 = "6yKpXV9bcSPuoBefgyVlGdAE39DnNKYJwBEYcbSbhIZwrhtVPkbPi8NiIbJ+iotVJCgZT/rczXMe/rqPJ3OmWA==";
      };
    };
    "@unocss/config-0.46.5" = {
      name = "_at_unocss_slash_config";
      packageName = "@unocss/config";
      version = "0.46.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/config/-/config-0.46.5.tgz";
        sha512 = "PCrT5GHyxaMroip8kLiX7vQDRYThugkAJNHHULWh/gWuvw5V/uMseeAisfMaRfNFXvtCRQeroNUggfAIXMNzxA==";
      };
    };
    "@unocss/config-0.60.3" = {
      name = "_at_unocss_slash_config";
      packageName = "@unocss/config";
      version = "0.60.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/config/-/config-0.60.3.tgz";
        sha512 = "3RGD7h3bS4qZA/Khcqhn1EgLgyPc85FSz5rubdywHRdHlpY9sdmuGEJahvqSLMN4MmdYQDmqEIEAJjENrdgZeQ==";
      };
    };
    "@unocss/core-0.46.5" = {
      name = "_at_unocss_slash_core";
      packageName = "@unocss/core";
      version = "0.46.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/core/-/core-0.46.5.tgz";
        sha512 = "apPWISH2ASKySyp4vBAkEzr5XNJDv4mu26eQ4wvg2a32cHRokUsiHLWFNMDe7oJquivTAOHsXqbLQuR9ePKNSg==";
      };
    };
    "@unocss/core-0.60.3" = {
      name = "_at_unocss_slash_core";
      packageName = "@unocss/core";
      version = "0.60.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/core/-/core-0.60.3.tgz";
        sha512 = "4bBX1pavDl2DSCozEII7bxYGT0IkyO7kKlUuCtooTePWyLjf2F7essdzHkJ00EpNR64kkebR9V0lqBMBo07VPw==";
      };
    };
    "@unocss/extractor-arbitrary-variants-0.60.3" = {
      name = "_at_unocss_slash_extractor-arbitrary-variants";
      packageName = "@unocss/extractor-arbitrary-variants";
      version = "0.60.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/extractor-arbitrary-variants/-/extractor-arbitrary-variants-0.60.3.tgz";
        sha512 = "PnwNwkeAHmbJbrf5XN0xQG1KT1VQEye8neYn5yz1MHnT8Cj2nqjrqoCRGLCLhpOUg3/MNj+bpiA7hGnFbXWaCQ==";
      };
    };
    "@unocss/preset-mini-0.46.5" = {
      name = "_at_unocss_slash_preset-mini";
      packageName = "@unocss/preset-mini";
      version = "0.46.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/preset-mini/-/preset-mini-0.46.5.tgz";
        sha512 = "pSiCUeNoLs9F5ux7BzsTKqQhTABvwtggv45Kza2wDIStPESLYHInPUHF57e753IhKdZSpX08gSRiYF4mXVcFWg==";
      };
    };
    "@unocss/preset-mini-0.60.3" = {
      name = "_at_unocss_slash_preset-mini";
      packageName = "@unocss/preset-mini";
      version = "0.60.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/preset-mini/-/preset-mini-0.60.3.tgz";
        sha512 = "7en8KBX3lN1Y6eCprbzA1QVfyXZD03B+oAxFXH8QPv5jRIL8Lm8sbXqE+VTsSME/OVp4DnS6LdGtDAm9mvIOSw==";
      };
    };
    "@unocss/preset-uno-0.46.5" = {
      name = "_at_unocss_slash_preset-uno";
      packageName = "@unocss/preset-uno";
      version = "0.46.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/preset-uno/-/preset-uno-0.46.5.tgz";
        sha512 = "O4f/cSdNAnK3MVXLgzihnOLrp12h3787U9bPZ1WS7Ow52D+kzBfRLVEWy4RWCGDN+ko/0q7Q7nqZOkrtcCELJQ==";
      };
    };
    "@unocss/preset-uno-0.60.3" = {
      name = "_at_unocss_slash_preset-uno";
      packageName = "@unocss/preset-uno";
      version = "0.60.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/preset-uno/-/preset-uno-0.60.3.tgz";
        sha512 = "PJSR78uaIRTsD9RFSQLwsrGAsjQoW5nWenU4n4GyZeskDsyQVgOcaKtvh+0aYjYdWBa1UvxeUL8Y+m29K4HnAA==";
      };
    };
    "@unocss/preset-wind-0.46.5" = {
      name = "_at_unocss_slash_preset-wind";
      packageName = "@unocss/preset-wind";
      version = "0.46.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/preset-wind/-/preset-wind-0.46.5.tgz";
        sha512 = "v1n918arr7qg/AYjkvVCJDqWT7bd8UhdT7tBCcJcFOuPvJdToBoy3LcNxQXQpS7gcVGG7YiKE5rT4JwsV7U5XA==";
      };
    };
    "@unocss/preset-wind-0.60.3" = {
      name = "_at_unocss_slash_preset-wind";
      packageName = "@unocss/preset-wind";
      version = "0.60.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/preset-wind/-/preset-wind-0.60.3.tgz";
        sha512 = "q7yDJ/SyEkPmPBJvIeHd9Bt50LAu65q7WwKxJYfJkjfJvJUMj6DO8FgPnpeiwBeJh9897m2Ap6zoQ3JqBjPLHQ==";
      };
    };
    "@unocss/rule-utils-0.60.3" = {
      name = "_at_unocss_slash_rule-utils";
      packageName = "@unocss/rule-utils";
      version = "0.60.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/rule-utils/-/rule-utils-0.60.3.tgz";
        sha512 = "I47/DcKQ2z12W80+Ffth0K6LzNvqcQPYRWk7KwVemVoEiGYamMV8/s+SbB26Fk9KUFjh+Ns/pGAo4iJZo0ueUQ==";
      };
    };
    "anymatch-3.1.3" = {
      name = "anymatch";
      packageName = "anymatch";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/anymatch/-/anymatch-3.1.3.tgz";
        sha512 = "KMReFUr0B4t+D+OBkjR3KYqvocp2XaSzO55UcB6mgQMd3KbcE+mWTyvVV7D/zsdEbNnV6acZUutkiHQXvTr1Rw==";
      };
    };
    "binary-extensions-2.3.0" = {
      name = "binary-extensions";
      packageName = "binary-extensions";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/binary-extensions/-/binary-extensions-2.3.0.tgz";
        sha512 = "Ceh+7ox5qe7LJuLHoY0feh3pHuUDHAcRUeyL2VYghZwfpkNIy/+8Ocg0a3UuSoYzavmylwuLWQOf3hl0jjMMIw==";
      };
    };
    "braces-3.0.3" = {
      name = "braces";
      packageName = "braces";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/braces/-/braces-3.0.3.tgz";
        sha512 = "yQbXgO/OSZVD2IsiLlro+7Hf6Q18EJrKSEsdoMzKePKXct3gvD8oLcOQdIzGupr5Fj+EDe8gO/lxc1BzfMpxvA==";
      };
    };
    "cac-6.7.14" = {
      name = "cac";
      packageName = "cac";
      version = "6.7.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/cac/-/cac-6.7.14.tgz";
        sha512 = "b6Ilus+c3RrdDk+JhLKUAQfzzgLEPy6wcXqS7f/xe1EETvsDP6GORG7SFuOs6cID5YkqchW/LXZbX5bc8j7ZcQ==";
      };
    };
    "chokidar-3.6.0" = {
      name = "chokidar";
      packageName = "chokidar";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chokidar/-/chokidar-3.6.0.tgz";
        sha512 = "7VT13fmjotKpGipCW9JEQAusEPE+Ei8nl6/g4FBAmIm0GOOLMua9NDDo/DWp0ZAxCr3cPq5ZpBqmPAQgDda2Pw==";
      };
    };
    "colorette-2.0.20" = {
      name = "colorette";
      packageName = "colorette";
      version = "2.0.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/colorette/-/colorette-2.0.20.tgz";
        sha512 = "IfEDxwoWIjkeXL1eXcDiow4UbKjhLdq6/EuSVR9GMN7KVH3r9gQ83e73hsz1Nd1T3ijd5xv1wcWRYO+D6kCI2w==";
      };
    };
    "consola-3.2.3" = {
      name = "consola";
      packageName = "consola";
      version = "3.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/consola/-/consola-3.2.3.tgz";
        sha512 = "I5qxpzLv+sJhTVEoLYNcTW+bThDCPsit0vLNKShZx6rLtpilNpmmeTPaeqJb9ZE9dV3DGaeby6Vuhrw38WjeyQ==";
      };
    };
    "defu-6.1.4" = {
      name = "defu";
      packageName = "defu";
      version = "6.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/defu/-/defu-6.1.4.tgz";
        sha512 = "mEQCMmwJu317oSz8CwdIOdwf3xMif1ttiM8LTufzc3g6kR+9Pe236twL8j3IYT1F7GfRgGcW6MWxzZjLIkuHIg==";
      };
    };
    "estree-walker-2.0.2" = {
      name = "estree-walker";
      packageName = "estree-walker";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/estree-walker/-/estree-walker-2.0.2.tgz";
        sha512 = "Rfkk/Mp/DL7JVje3u18FxFujQlTNR2q6QfMSMB7AvCBx91NGj/ba3kCfza0f6dVDbw7YlRf/nDrn7pQrCCyQ/w==";
      };
    };
    "fast-glob-3.3.2" = {
      name = "fast-glob";
      packageName = "fast-glob";
      version = "3.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-glob/-/fast-glob-3.3.2.tgz";
        sha512 = "oX2ruAFQwf/Orj8m737Y5adxDQO0LAB7/S5MnxCdTNDd4p6BsyIVsv9JQsATbTSq8KHRpLwIHbVlUNatxd+1Ow==";
      };
    };
    "fastq-1.17.1" = {
      name = "fastq";
      packageName = "fastq";
      version = "1.17.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fastq/-/fastq-1.17.1.tgz";
        sha512 = "sRVD3lWVIXWg6By68ZN7vho9a1pQcN/WBFaAAsDDFzlJjvoGx0P8z7V1t72grFJfJhu3YPZBuu25f7Kaw2jN1w==";
      };
    };
    "fill-range-7.1.1" = {
      name = "fill-range";
      packageName = "fill-range";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fill-range/-/fill-range-7.1.1.tgz";
        sha512 = "YsGpe3WHLK8ZYi4tWDg2Jy3ebRz2rXowDxnld4bkQB00cc/1Zw9AWnC0i9ztDJitivtQvaI9KaLyKrc+hBW0yg==";
      };
    };
    "glob-parent-5.1.2" = {
      name = "glob-parent";
      packageName = "glob-parent";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-parent/-/glob-parent-5.1.2.tgz";
        sha512 = "AOIgSQCepiJYwP3ARnGx+5VnTu2HBYdzbGP45eLw1vr3zB3vZLeyed1sC9hnbcOc9/SrMyM5RPQrkGz4aS9Zow==";
      };
    };
    "is-binary-path-2.1.0" = {
      name = "is-binary-path";
      packageName = "is-binary-path";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-binary-path/-/is-binary-path-2.1.0.tgz";
        sha512 = "ZMERYes6pDydyuGidse7OsHxtbI7WVeUEozgR/g7rd0xUimYNlvZRE/K2MgZTjWy725IfelLeVcEM97mmtRGXw==";
      };
    };
    "is-extglob-2.1.1" = {
      name = "is-extglob";
      packageName = "is-extglob";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extglob/-/is-extglob-2.1.1.tgz";
        sha512 = "SbKbANkN603Vi4jEZv49LeVJMn4yGwsbzZworEoyEiutsN3nJYdbO36zfhGJ6QEDpOZIFkDtnq5JRxmvl3jsoQ==";
      };
    };
    "is-glob-4.0.3" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-4.0.3.tgz";
        sha512 = "xelSayHH36ZgE7ZWhli7pW34hNbNl8Ojv5KVmkJD4hBdD3th8Tfk9vYasLM+mXWOZhFkgZfxhLSnrwRr4elSSg==";
      };
    };
    "is-number-7.0.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-7.0.0.tgz";
        sha512 = "41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==";
      };
    };
    "jiti-1.21.0" = {
      name = "jiti";
      packageName = "jiti";
      version = "1.21.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jiti/-/jiti-1.21.0.tgz";
        sha512 = "gFqAIbuKyyso/3G2qhiO2OM6shY6EPP/R0+mkDbyspxKazh8BXDC5FiFsUjlczgdNz/vfra0da2y+aHrusLG/Q==";
      };
    };
    "lru-cache-7.18.3" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "7.18.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-7.18.3.tgz";
        sha512 = "jumlc0BIUrS3qJGgIkWZsyfAM7NCWiBcCDhnd+3NNM5KbBmLTgHVfWBcg6W+rLUsIpzpERPsvwUP7CckAQSOoA==";
      };
    };
    "magic-string-0.30.10" = {
      name = "magic-string";
      packageName = "magic-string";
      version = "0.30.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/magic-string/-/magic-string-0.30.10.tgz";
        sha512 = "iIRwTIf0QKV3UAnYK4PU8uiEc4SRh5jX0mwpIwETPpHdhVM4f53RSwS/vXvN1JhGX+Cs7B8qIq3d6AH49O5fAQ==";
      };
    };
    "merge2-1.4.1" = {
      name = "merge2";
      packageName = "merge2";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge2/-/merge2-1.4.1.tgz";
        sha512 = "8q7VEgMJW4J8tcfVPy8g09NcQwZdbwFEqhe/WZkoIzjn/3TGDwtOCYtXGxA3O8tPzpczCCDgv+P2P5y00ZJOOg==";
      };
    };
    "micromatch-4.0.7" = {
      name = "micromatch";
      packageName = "micromatch";
      version = "4.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromatch/-/micromatch-4.0.7.tgz";
        sha512 = "LPP/3KorzCwBxfeUuZmaR6bG2kdeHSbe0P2tY3FLRU4vYrjYz5hI4QZwV0njUx3jeuKe67YukQ1LSPZBKDqO/Q==";
      };
    };
    "normalize-path-3.0.0" = {
      name = "normalize-path";
      packageName = "normalize-path";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-path/-/normalize-path-3.0.0.tgz";
        sha512 = "6eZs5Ls3WtCisHWp9S2GUy8dqkpGi4BVSz3GaqiE6ezub0512ESztXUwUB6C6IKbQkY2Pnb/mD4WYojCRwcwLA==";
      };
    };
    "pathe-1.1.2" = {
      name = "pathe";
      packageName = "pathe";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pathe/-/pathe-1.1.2.tgz";
        sha512 = "whLdWMYL2TwI08hn8/ZqAbrVemu0LNaNNJZX73O6qaIdCTfXutsLhMkjdENX0qhsQ9uIimo4/aQOmXkoon2nDQ==";
      };
    };
    "perfect-debounce-1.0.0" = {
      name = "perfect-debounce";
      packageName = "perfect-debounce";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/perfect-debounce/-/perfect-debounce-1.0.0.tgz";
        sha512 = "xCy9V055GLEqoFaHoC1SoLIaLmWctgCUaBaWxDZ7/Zx4CTyX7cJQLJOok/orfjZAh9kEYpjJa4d0KcJmCbctZA==";
      };
    };
    "picomatch-2.3.1" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-2.3.1.tgz";
        sha512 = "JU3teHTNjmE2VCGFzuY8EXzCDVwEqB2a8fsIvwaStHhAWJEeVd1o1QD80CU6+ZdEXXSLbSsuLwJjkCBWqRQUVA==";
      };
    };
    "queue-microtask-1.2.3" = {
      name = "queue-microtask";
      packageName = "queue-microtask";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/queue-microtask/-/queue-microtask-1.2.3.tgz";
        sha512 = "NuaNSa6flKT5JaSYQzJok04JzTL1CA6aGhv5rfLW3PgqA+M2ChpZQnAC8h8i4ZFkBS8X5RqkDBHA7r4hej3K9A==";
      };
    };
    "readdirp-3.6.0" = {
      name = "readdirp";
      packageName = "readdirp";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readdirp/-/readdirp-3.6.0.tgz";
        sha512 = "hOS089on8RduqdbhvQ5Z37A0ESjsqz6qnRcffsMU3495FuTdqSm+7bhJ29JvIOsBDEEnan5DPu9t3To9VRlMzA==";
      };
    };
    "reusify-1.0.4" = {
      name = "reusify";
      packageName = "reusify";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/reusify/-/reusify-1.0.4.tgz";
        sha512 = "U9nH88a3fc/ekCF1l0/UP1IosiuIjyTh7hBvXVMHYgVcfGvt897Xguj2UOLDeI5BG2m7/uwyaLVT6fbtCwTyzw==";
      };
    };
    "rollup-4.18.0" = {
      name = "rollup";
      packageName = "rollup";
      version = "4.18.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/rollup/-/rollup-4.18.0.tgz";
        sha512 = "QmJz14PX3rzbJCN1SG4Xe/bAAX2a6NpCP8ab2vfu2GiUr8AQcr2nCV/oEO3yneFarB67zk8ShlIyWb2LGTb3Sg==";
      };
    };
    "run-parallel-1.2.0" = {
      name = "run-parallel";
      packageName = "run-parallel";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/run-parallel/-/run-parallel-1.2.0.tgz";
        sha512 = "5l4VyZR86LZ/lDxZTR6jqL8AFE2S0IFLMP26AbjsLVADxHdhB/c0GUsH+y39UfCi3dzz8OlQuPmnaJOMoDHQBA==";
      };
    };
    "to-regex-range-5.0.1" = {
      name = "to-regex-range";
      packageName = "to-regex-range";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-regex-range/-/to-regex-range-5.0.1.tgz";
        sha512 = "65P7iz6X5yEr1cwcgvQxbbIw7Uk3gOy5dIdtZ4rDveLqhrdJP+Li/Hx6tyK0NEb+2GCyneCMJiGqrADCSNk8sQ==";
      };
    };
    "unconfig-0.3.13" = {
      name = "unconfig";
      packageName = "unconfig";
      version = "0.3.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/unconfig/-/unconfig-0.3.13.tgz";
        sha512 = "N9Ph5NC4+sqtcOjPfHrRcHekBCadCXWTBzp2VYYbySOHW0PfD9XLCeXshTXjkPYwLrBr9AtSeU0CZmkYECJhng==";
      };
    };
    "vscode-jsonrpc-6.0.0" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-6.0.0.tgz";
        sha512 = "wnJA4BnEjOSyFMvjZdpiOwhSq9uDoK8e/kpRJDTaMYzwlkrhG1fwDIZI94CLsLzlCK5cIbMMtFlJlfR57Lavmg==";
      };
    };
    "vscode-languageserver-7.0.0" = {
      name = "vscode-languageserver";
      packageName = "vscode-languageserver";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver/-/vscode-languageserver-7.0.0.tgz";
        sha512 = "60HTx5ID+fLRcgdHfmz0LDZAXYEV68fzwG0JWwEPBode9NuMYTIxuYXPg4ngO8i8+Ou0lM7y6GzaYWbiDL0drw==";
      };
    };
    "vscode-languageserver-protocol-3.16.0" = {
      name = "vscode-languageserver-protocol";
      packageName = "vscode-languageserver-protocol";
      version = "3.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.16.0.tgz";
        sha512 = "sdeUoAawceQdgIfTI+sdcwkiK2KU+2cbEYA0agzM2uqaUy2UpnnGHtWTHVEtS0ES4zHU0eMFRGN+oQgDxlD66A==";
      };
    };
    "vscode-languageserver-textdocument-1.0.11" = {
      name = "vscode-languageserver-textdocument";
      packageName = "vscode-languageserver-textdocument";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-textdocument/-/vscode-languageserver-textdocument-1.0.11.tgz";
        sha512 = "X+8T3GoiwTVlJbicx/sIAF+yuJAqz8VvwJyoMVhwEMoEKE/fkDmrqUgDMyBECcM2A2frVZIUj5HI/ErRXCfOeA==";
      };
    };
    "vscode-languageserver-types-3.16.0" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.16.0.tgz";
        sha512 = "k8luDIWJWyenLc5ToFQQMaSrqCHiLwyKPHKPQZ5zz21vM+vIVUSvsRpcbiECH4WR88K2XZqc4ScRcZ7nk/jbeA==";
      };
    };
  };
in
{
  "@unocss/cli" = nodeEnv.buildNodePackage {
    name = "_at_unocss_slash_cli";
    packageName = "@unocss/cli";
    version = "0.60.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/@unocss/cli/-/cli-0.60.3.tgz";
      sha512 = "bN829zn6k4hrvDTLnUcI2uAJnSevHwlkOCaYxN/C+v11uGxIewk5Xum6Vm5kZ8JTpCR1jEu/i7wIBNde3XKN5g==";
    };
    dependencies = [
      sources."@ampproject/remapping-2.3.0"
      sources."@antfu/utils-0.7.8"
      sources."@jridgewell/gen-mapping-0.3.5"
      sources."@jridgewell/resolve-uri-3.1.2"
      sources."@jridgewell/set-array-1.2.1"
      sources."@jridgewell/sourcemap-codec-1.4.15"
      sources."@jridgewell/trace-mapping-0.3.25"
      sources."@nodelib/fs.scandir-2.1.5"
      sources."@nodelib/fs.stat-2.0.5"
      sources."@nodelib/fs.walk-1.2.8"
      sources."@rollup/pluginutils-5.1.0"
      sources."@types/estree-1.0.5"
      sources."@unocss/config-0.60.3"
      sources."@unocss/core-0.60.3"
      sources."@unocss/extractor-arbitrary-variants-0.60.3"
      sources."@unocss/preset-mini-0.60.3"
      sources."@unocss/preset-uno-0.60.3"
      sources."@unocss/preset-wind-0.60.3"
      sources."@unocss/rule-utils-0.60.3"
      sources."anymatch-3.1.3"
      sources."binary-extensions-2.3.0"
      sources."braces-3.0.3"
      sources."cac-6.7.14"
      sources."chokidar-3.6.0"
      sources."colorette-2.0.20"
      sources."consola-3.2.3"
      sources."defu-6.1.4"
      sources."estree-walker-2.0.2"
      sources."fast-glob-3.3.2"
      sources."fastq-1.17.1"
      sources."fill-range-7.1.1"
      sources."glob-parent-5.1.2"
      sources."is-binary-path-2.1.0"
      sources."is-extglob-2.1.1"
      sources."is-glob-4.0.3"
      sources."is-number-7.0.0"
      sources."jiti-1.21.0"
      sources."magic-string-0.30.10"
      sources."merge2-1.4.1"
      sources."micromatch-4.0.7"
      sources."normalize-path-3.0.0"
      sources."pathe-1.1.2"
      sources."perfect-debounce-1.0.0"
      sources."picomatch-2.3.1"
      sources."queue-microtask-1.2.3"
      sources."readdirp-3.6.0"
      sources."reusify-1.0.4"
      sources."rollup-4.18.0"
      sources."run-parallel-1.2.0"
      sources."to-regex-range-5.0.1"
      sources."unconfig-0.3.13"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "CLI for UnoCSS";
      homepage = "https://github.com/unocss/unocss/tree/main/packages/cli#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  unocss-language-server = nodeEnv.buildNodePackage {
    name = "unocss-language-server";
    packageName = "unocss-language-server";
    version = "0.0.10";
    src = fetchurl {
      url = "https://registry.npmjs.org/unocss-language-server/-/unocss-language-server-0.0.10.tgz";
      sha512 = "WRHKrpx9fC99MAb6Rt4nSgJ51X72xJpwvcur9BXMNEXs6cIeV/7+uD+5NzLMawZK1BthkdjChMXURB1gwOfn3A==";
    };
    dependencies = [
      sources."@antfu/utils-0.7.8"
      sources."@unocss/autocomplete-0.46.5"
      sources."@unocss/config-0.46.5"
      sources."@unocss/core-0.46.5"
      sources."@unocss/preset-mini-0.46.5"
      sources."@unocss/preset-uno-0.46.5"
      sources."@unocss/preset-wind-0.46.5"
      sources."defu-6.1.4"
      sources."jiti-1.21.0"
      sources."lru-cache-7.18.3"
      sources."unconfig-0.3.13"
      sources."vscode-jsonrpc-6.0.0"
      sources."vscode-languageserver-7.0.0"
      sources."vscode-languageserver-protocol-3.16.0"
      sources."vscode-languageserver-textdocument-1.0.11"
      sources."vscode-languageserver-types-3.16.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "unocss language server";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
